version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.4.0
  circleci-images: circleci/circleci-images@dev:alpha

jobs:
  android:
    parameters:
      tag:
        type: string
        description: circleci/android tag

      ndk-version:
        type: string
        description: ndk version to install

    resource_class: small
    docker:
      - image: circleci/android:<<parameters.tag>>

    steps:
      - checkout

      - circleci-images/install-android-ndk:
          ndk-version: <<parameters.ndk-version>>

prod-deploy_requires: &prod-deploy_requires
  [17c-23-master, 17c-24-master, 17c-25-master, 17c-26-master, 17c-27-master, 17c-28-master, 18b-23-master, 18b-24-master, 18b-25-master, 18b-26-master, 18b-27-master, 18b-28-master, 19c-23-master, 19c-24-master, 19c-25-master, 19c-26-master, 19c-27-master, 19c-28-master]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: circleci/circleci-images
          context: orb-publishing
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          ssh-fingerprints: c7:36:9a:0e:3b:cb:ed:6c:bb:a8:93:69:62:50:59:db
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          context: orb-publishing
          ssh-fingerprints: c7:36:9a:0e:3b:cb:ed:6c:bb:a8:93:69:62:50:59:db
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      # triggered by non-master branch commits
      # 17c
      - android:
          name: 17c-23-dev
          tag: api-23
          ndk-version: android-ndk-r17c

      - android:
          name: 17c-24-dev
          tag: api-24
          ndk-version: android-ndk-r17c

      - android:
          name: 17c-25-dev
          tag: api-25
          ndk-version: android-ndk-r17c

      - android:
          name: 17c-26-dev
          tag: api-26
          ndk-version: android-ndk-r17c

      - android:
          name: 17c-27-dev
          tag: api-27
          ndk-version: android-ndk-r17c

      - android:
          name: 17c-28-dev
          tag: api-28
          ndk-version: android-ndk-r17c

      # 18b
      - android:
          name: 18b-23-dev
          tag: api-23
          ndk-version: android-ndk-r18b

      - android:
          name: 18b-24-dev
          tag: api-24
          ndk-version: android-ndk-r18b

      - android:
          name: 18b-25-dev
          tag: api-25
          ndk-version: android-ndk-r18b

      - android:
          name: 18b-26-dev
          tag: api-26
          ndk-version: android-ndk-r18b

      - android:
          name: 18b-27-dev
          tag: api-27
          ndk-version: android-ndk-r18b

      - android:
          name: 18b-28-dev
          tag: api-28
          ndk-version: android-ndk-r18b

      # 19c
      - android:
          name: 19c-23-dev
          tag: api-23
          ndk-version: android-ndk-r19c

      - android:
          name: 19c-24-dev
          tag: api-24
          ndk-version: android-ndk-r19c

      - android:
          name: 19c-25-dev
          tag: api-25
          ndk-version: android-ndk-r19c

      - android:
          name: 19c-26-dev
          tag: api-26
          ndk-version: android-ndk-r19c

      - android:
          name: 19c-27-dev
          tag: api-27
          ndk-version: android-ndk-r19c

      - android:
          name: 19c-28-dev
          tag: api-28
          ndk-version: android-ndk-r19c

      # triggered by master branch commits
      # 17c
      - android:
          name: 17c-23-master
          tag: api-23
          ndk-version: android-ndk-r17c

      - android:
          name: 17c-24-master
          tag: api-24
          ndk-version: android-ndk-r17c

      - android:
          name: 17c-25-master
          tag: api-25
          ndk-version: android-ndk-r17c

      - android:
          name: 17c-26-master
          tag: api-26
          ndk-version: android-ndk-r17c

      - android:
          name: 17c-27-master
          tag: api-27
          ndk-version: android-ndk-r17c

      - android:
          name: 17c-28-master
          tag: api-28
          ndk-version: android-ndk-r17c

      # 18b
      - android:
          name: 18b-23-master
          tag: api-23
          ndk-version: android-ndk-r18b

      - android:
          name: 18b-24-master
          tag: api-24
          ndk-version: android-ndk-r18b

      - android:
          name: 18b-25-master
          tag: api-25
          ndk-version: android-ndk-r18b

      - android:
          name: 18b-26-master
          tag: api-26
          ndk-version: android-ndk-r18b

      - android:
          name: 18b-27-master
          tag: api-27
          ndk-version: android-ndk-r18b

      - android:
          name: 18b-28-master
          tag: api-28
          ndk-version: android-ndk-r18b

      # 19c
      - android:
          name: 19c-23-master
          tag: api-23
          ndk-version: android-ndk-r19c

      - android:
          name: 19c-24-master
          tag: api-24
          ndk-version: android-ndk-r19c

      - android:
          name: 19c-25-master
          tag: api-25
          ndk-version: android-ndk-r19c

      - android:
          name: 19c-26-master
          tag: api-26
          ndk-version: android-ndk-r19c

      - android:
          name: 19c-27-master
          tag: api-27
          ndk-version: android-ndk-r19c

      - android:
          name: 19c-28-master
          tag: api-28
          ndk-version: android-ndk-r19c

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/circleci-images
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          context: orb-publishing
          orb-name: circleci/circleci-images
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          context: orb-publishing
          orb-name: circleci/circleci-images
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
